#
# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)
CPPFLAGS += -DAUDIO -DAUTOSOURCE -DAUTOSWITCH -DCORRECT_NEGATIVE_SHIFTS -DCPUESP32 -DCURVES -DDBLKEYS -DEEPROM -DEEPROM_RLC -DEEPROM_VARIANT=0 -DFLAVOUR=\"esp_wroom_32\" -DFLIGHT_MODES -DFONT="" -DGUI -DGVARS -DHELI -DLCD_SPI -DOVERRIDE_CHANNEL_FUNCTION -DPCBESP_WROOM_32 -DPPM_CENTER_ADJUSTABLE -DPPM_UNIT_PERCENT_PREC1 -DROTARY_ENCODERS=1 -DSPLASH -DTRACE_SIMPGMSPACE -DTRANSLATIONS=\"EN\" -DTRANSLATIONS_EN

